name: flutter_app
description: Application with flutter.

version: 2.0.3+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # Notification
  #  flutter_local_notifications: ^12.0.0
  #  firebase_messaging: ^14.1.1
  # Firebase
  # firebase_core: ^2.7.1
  #  firebase_analytics: ^9.3.5
  #  cloud_firestore: ^3.4.8
  #  firebase_storage: ^10.3.8
  #  firebase_auth: ^3.9.0
  # firebase_crashlytics: ^3.0.16
  #Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  logger: ^1.3.0

  #Boilerplate
  get_it: ^7.7.0
  hive: ^2.2.3
  # get: ^4.6.5
  # get_storage: ^2.1.1
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_strategy: ^0.2.0

  #Other
  flutter_svg: ^2.0.6
  device_info_plus: ^9.0.1
  intl: ^0.18.1
  url_launcher: ^6.2.5
  google_fonts: ^5.1.0
  gif_view: ^0.4.3
  pretty_qr_code: ^3.3.0
  flutter_timer_countdown: ^1.0.7
  flutter_web3: ^2.1.9
  js: ^0.6.7
  youtube_player_iframe: ^5.1.2
  currency_text_input_formatter: ^2.2.1
  flutter_rounded_progress_bar: ^0.3.2
  lottie: ^3.1.0
  hexagon: ^0.2.0
  infinite_carousel: ^1.1.1
  easy_image_viewer: ^1.5.0
  go_router: ^14.1.0
  flutter_widget_from_html: ^0.15.0

dev_dependencies:
  flutter_lints: ^2.0.1

#flutter_icons:
#  image_path: "assets/icon.png"
#  android: true
#  ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/svg/
    - assets/images/gif/
    - assets/images/lottie/
flutter_intl:
  enabled: true
